// File: src/types/mealPlan.ts

export type MealPlanFocus = 'DAILY' | 'HIGH_PROTEIN' | 'LOW_CARB' | 'BALANCED' | 'BUDGET_FRIENDLY';

/**
 * Matches com.nutriguideai.dto.request.MealPlanRequest
 */
export interface MealPlanRequest {
    days: number;
    mealsPerDay: number;
    focus?: MealPlanFocus;
}

/**
 * Matches com.nutriguideai.dto.response.MealPlanDetailResponse
 */
export interface MealPlanDetailResponse {
    id: number;
    planDate: string;
    totalCalories: number;
    totalProtein: number;
    totalCarbs: number;
    totalFat: number;
    /** Markdown text generated by the AI Nutrition Service */
    plan: string;
    generatedAt: string;
}

export interface MealPlanHistoryResponse {
    plans: MealPlanDetailResponse[];
    total: number;
}