server:
  port: 8081

spring:
  application:
    name: NutirGuideAI
    spring:
      jpa:
        open-in-view: false
        hibernate:
          ddl-auto: update
        show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/nutriguide_ai
    username: root
    password: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: ThisIsASecretKeyForJwtAuthentication12345678901234567890
    expiration-ms: 86400000

    spring doc:
      swagger-ui:
        operations-sorter: method
        tags-sorter: alpha
      api-docs:
        path: /v3/api-docs
