package com.nutriguideai.dto.response;

import com.nutriguideai.entity.User;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;

@Getter
@Builder
@AllArgsConstructor
@Schema(description = "Successful login — JWT token plus the user profile.")
public class LoginResponse {

    @Schema(
            description = "JWT bearer token. Send as Authorization: Bearer <token>",
            example = "eyJhbGciOiJIUzI1NiJ9..."
    )
    private final String token;

    @Schema(
            description = "Always \"Bearer\"",
            example = "Bearer"
    )
    private final String tokenType;

    @Schema(
            description = "Opaque refresh token, exchanged at POST /api/auth/refresh for a new pair",
            example = "kY2xv2L..."
    )
    private final String refreshToken;

    @Schema(
            description = "The authenticated user's profile",
            implementation = UserResponse.class
    )
    private final UserResponse user;

    /**
     * Builds the login response after successful authentication.
     * The access token is generated by JwtTokenProvider; the refresh
     * token is the raw opaque value issued by AuthServiceImpl — this
     * DTO never sees the raw password.
     */
    public static LoginResponse of(String token, String refreshToken, User user) {
        return LoginResponse.builder()
                .token(token)
                .tokenType("Bearer")
                .refreshToken(refreshToken)
                .user(UserResponse.fromEntity(user))
                .build();
    }
}