package com.nutriguideai.dto.response;



import com.nutriguideai.entity.User;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;

@Getter
@Builder
@AllArgsConstructor
public class LoginResponse {

    private final String token;
    private final String tokenType;
    private final UserResponse user;

    /**
     * Builds the login response after successful authentication.
     * The token is generated by JwtTokenProvider and passed in —
     * this DTO never generates or sees the raw password.
     */
    public static LoginResponse of(String token, User user) {
        return LoginResponse.builder()
                .token(token)
                .tokenType("Bearer")
                .user(UserResponse.fromEntity(user))
                .build();
    }
}